export const LOAD_RECORDS_LIST = "LOAD_RECORDS_LIST";
export const LOAD_NEW_RECORD = "LOAD_NEW_RECORD";
export const FETCH_EDIT_SINGLE_RECORD = "FETCH_EDIT_SINGLE_RECORD";
export const FETCH_DELETE_SINGLE_RECORD = "FETCH_DELETE_SINGLE_RECORD";
export const FETCH_LOGIN = "FETCH_LOGIN";
export const FETCH_REG = "FETCH_REG";
export const FETCH_SESSION = "FETCH_SESSION";
export const FETCH_UPDATE_LIST = "FETCH_UPDATE_LIST";