export const LOAD_RECORDS = "LOAD_RECORDS";
export const REQUEST_FAIL_ACTION = "REQUEST_FAIL_ACTION";
export const ADD_NEW_RECORD = "ADD_NEW_RECORD";
export const CLEAR_STATUS = "CLEAR_STATUS";
export const EDIT_RECORD = "EDIT_RECORD";
export const DONE_REG = "DONE_REG";
export const DELETE_RECORD_DONE = "DELETE_RECORD_DONE";
export const LOAD_SESSION = "LOAD_SESSION";